# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IPL' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IPL
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end
